#!/bin/bash

echo "🔐 GitHub Personal Access Token設定スクリプト"
echo "============================================="
echo ""
echo "手順:"
echo "1. GitHubでPersonal Access Tokenを作成済みであることを確認"
echo "2. 以下のコマンドを実行（YOUR_TOKENを実際のトークンに置換）"
echo ""
echo "# リモートURL更新（YOUR_TOKENを実際のトークンに置換してください）"
echo "git remote set-url origin https://okumurakoki:YOUR_TOKEN@github.com/okumurakoki/hajimete-ai.git"
echo ""
echo "# プッシュ実行"
echo "git push origin main"
echo ""
echo "# 成功確認"
echo "git log --oneline -1"
echo ""
echo "⚠️  YOUR_TOKENの部分を、GitHubで生成した実際のPersonal Access Tokenに置換してください"
echo "    例: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"